import type{ReportRequest}from"@classmate/shared";import{spawn}from"node:child_process";import{writeFile}from"node:fs/promises";import{resolve}from"node:path";import{config}from"../shared/config.js";import{DependencyError,NotFoundError}from"../shared/errors.js";import{eventBus}from"../shared/event-bus.js";import{fingerprint}from"../shared/ids.js";import{getAiProvider}from"../ai/provider.js";import{JobRepository}from"../jobs/job.repository.js";import{ReportRepository,type ReportRow}from"./report.repository.js";
export class ReportService{constructor(private readonly repository:ReportRepository,private readonly jobs:JobRepository){}
request(courseId:string,input:ReportRequest={},kind="comprehensive"):ReportRow{const report=this.repository.create(courseId,input,kind);this.jobs.enqueue("generate_report",{reportId:report.id},fingerprint("report",report.id));return report;}
list(courseId:string):ReportRow[]{return this.repository.list(courseId)}
async generate(reportId:string):Promise<void>{const report=this.repository.find(reportId);if(!report)throw new NotFoundError("Report",reportId);try{const packet=this.repository.evidence(report.courseId,report.scopeStartDay,report.scopeEndDay),prompt=buildPrompt(packet,report);const target=Math.min(3000,Math.max(1200,packet.sessions.length*450));const content=await getAiProvider().answer("你是严谨的中文综合学习报告编辑。所有课程事实必须来自证据包；不虚构日期、教师要求或完成结果。可以写学习反思，但要标明为个人理解。输出 Markdown，使用一级标题作为报告标题、二级标题组织章节、三级标题组织每次课堂内容。报告周期由证据范围决定，不假定固定天数。",`${prompt}\n\n建议正文长度约 ${target} 个中文字符。`);const artifact=toArtifact(report.title,packet.course.name,content,packet.sessions.length,scopeLabel(report));const input=resolve(config.outputDir,`${report.id}.json`);await writeFile(input,JSON.stringify(artifact,null,2),"utf8");const docx=resolve(config.outputDir,"docx",`${report.id}.docx`),pdf=resolve(config.outputDir,"pdf",`${report.id}.pdf`);await run(config.executables.docxExport,["--input",input,"--output",docx]);await run(config.executables.python,[resolve(config.root,"services/ai-worker/main.py"),"export-pdf","--input",input,"--output",pdf]);this.repository.complete(reportId,content,docx,pdf);eventBus.publish({type:"report",payload:{reportId,status:"completed",docx,pdf}});}catch(error){this.repository.fail(reportId);throw error;}}
}
function buildPrompt(packet:{course:any;sessions:any[];tasks:any[]},report:ReportRow):string{const sessions=packet.sessions.map(s=>{const events=s.events.map((e:any)=>`- [${e.type}|重要度${e.importance}] ${e.title}: ${e.content}`).join("\n");const transcript=s.transcript.slice(0,80).map((t:any)=>`- ${formatMs(t.start_ms)} ${t.text}`).join("\n");return `## 第${s.day_index}课次 ${s.title}\n状态:${s.status}\n增量日报:\n${s.summary??"无"}\n事件:\n${events||"无结构化事件"}\n字幕摘录:\n${transcript||"无字幕"}`}).join("\n\n");const tasks=packet.tasks.map(t=>`- ${t.title}: ${t.detail}; 截止原话:${t.deadline_raw??"无"}; 状态:${t.status}`).join("\n");return `课程：${packet.course.name}\n教师：${packet.course.instructor??"未记录"}\n报告范围：${scopeLabel(report)}\n纳入课堂：${packet.sessions.length} 次\n\n${sessions}\n\n## 任务证据\n${tasks||"无"}\n\n请生成：学习目标、环境与方法、逐次学习内容、核心知识体系、任务与实践、学习反思、总结。只写入所选范围内实际存在的课堂，不为课次编号空缺补写内容。`;}
function scopeLabel(report:ReportRow):string{return report.scopeStartDay===null&&report.scopeEndDay===null?"全部已记录课堂":`第 ${report.scopeStartDay??1}-${report.scopeEndDay??365} 课次`;}
function toArtifact(title:string,course:string,markdown:string,sessions:number,scope:string){const sections:Array<{heading:string;level:number;paragraphs:string[]}>=[];let current={heading:"报告说明",level:1,paragraphs:[]as string[]};for(const block of markdown.split(/\n\s*\n/)){const heading=block.match(/^(#{1,3})\s+(.+)$/);if(heading){if(current.paragraphs.length||current.heading!=="报告说明")sections.push(current);current={heading:heading[2]!.trim(),level:heading[1]!.length,paragraphs:[]};}else{const cleaned=block.replace(/^[-*]\s+/gm,"• ").trim();if(cleaned)current.paragraphs.push(cleaned);}}if(current.paragraphs.length||current.heading!=="报告说明")sections.push(current);return{title,subtitle:`${course} · ${scope} · ${sessions} 次课堂证据`,author:"Classmate Agent（待学生审核）",generatedAt:new Date().toISOString(),sections};}
function run(command:string,args:string[]):Promise<void>{return new Promise((ok,fail)=>{const child=spawn(command,args,{windowsHide:true});let stderr="";child.stderr.on("data",d=>stderr+=d);child.on("error",e=>fail(new DependencyError(`无法启动导出器 ${command}: ${e.message}`)));child.on("close",code=>code===0?ok():fail(new DependencyError(`导出器失败(${code}): ${stderr.trim()}`)));});}
function formatMs(ms:number):string{const t=Math.floor(ms/1000);return`${String(Math.floor(t/60)).padStart(2,"0")}:${String(t%60).padStart(2,"0")}`}
