import type{ReportRequest}from"@classmate/shared";import{db}from"../shared/database.js";import{CourseRepository}from"../courses/course.repository.js";import{NotFoundError,ValidationError}from"../shared/errors.js";import{id}from"../shared/ids.js";
export type ReportRow={id:string;courseId:string;kind:string;title:string;contentMd:string;docxPath:string|null;pdfPath:string|null;status:string;scopeStartDay:number|null;scopeEndDay:number|null;createdAt:string;updatedAt:string};
const map=(r:any):ReportRow=>({id:r.id,courseId:r.course_id,kind:r.kind,title:r.title,contentMd:r.content_md,docxPath:r.docx_path,pdfPath:r.pdf_path,status:r.status,scopeStartDay:r.scope_start_day??null,scopeEndDay:r.scope_end_day??null,createdAt:r.created_at,updatedAt:r.updated_at});
export class ReportRepository{constructor(private readonly courses:CourseRepository){}
create(courseId:string,input:ReportRequest={},kind="comprehensive"):ReportRow{const course=this.courses.find(courseId);if(!course)throw new NotFoundError("Course",courseId);const count=(db.prepare("SELECT count(*) count FROM sessions WHERE course_id=? AND (? IS NULL OR day_index>=?) AND (? IS NULL OR day_index<=?)").get(courseId,input.startDay??null,input.startDay??null,input.endDay??null,input.endDay??null)as{count:number}).count;if(!count)throw new ValidationError("所选范围内没有课堂记录");const now=new Date().toISOString(),range=input.startDay!==undefined||input.endDay!==undefined?`（第 ${input.startDay??1}-${input.endDay??365} 课次）`:"";const row:ReportRow={id:id("report"),courseId,kind,title:input.title??`${course.name}${range}综合学习报告`,contentMd:"",docxPath:null,pdfPath:null,status:"pending",scopeStartDay:input.startDay??null,scopeEndDay:input.endDay??null,createdAt:now,updatedAt:now};db.prepare(`INSERT INTO reports(id,course_id,kind,title,content_md,source_summary_ids_json,docx_path,pdf_path,status,scope_start_day,scope_end_day,created_at,updated_at) VALUES (?,?,?,?,?,'[]',?,?,?,?,?,?,?)`).run(row.id,row.courseId,row.kind,row.title,row.contentMd,row.docxPath,row.pdfPath,row.status,row.scopeStartDay,row.scopeEndDay,row.createdAt,row.updatedAt);return row;}
list(courseId:string):ReportRow[]{return(db.prepare("SELECT * FROM reports WHERE course_id=? ORDER BY created_at DESC").all(courseId)as any[]).map(map)}
find(reportId:string):ReportRow|null{const r=db.prepare("SELECT * FROM reports WHERE id=?").get(reportId);return r?map(r):null}
evidence(courseId:string,startDay:number|null=null,endDay:number|null=null):{course:any;sessions:any[];tasks:any[]}{const course=this.courses.find(courseId);if(!course)throw new NotFoundError("Course",courseId);const sessions=(db.prepare("SELECT * FROM sessions WHERE course_id=? AND (? IS NULL OR day_index>=?) AND (? IS NULL OR day_index<=?) ORDER BY day_index").all(courseId,startDay,startDay,endDay,endDay)as any[]).map(s=>({...s,summary:(db.prepare("SELECT content_md FROM summaries WHERE session_id=? AND level='session'").get(s.id)as any)?.content_md??null,events:(db.prepare("SELECT type,title,content,importance,confidence,evidence_json FROM semantic_events WHERE session_id=? ORDER BY created_at").all(s.id)as any[]),transcript:(db.prepare("SELECT start_ms,end_ms,text FROM transcript_segments WHERE session_id=? ORDER BY sequence").all(s.id)as any[])}));const tasks=db.prepare("SELECT title,detail,deadline_raw,status,importance FROM tasks WHERE course_id=? AND (? IS NULL OR EXISTS(SELECT 1 FROM sessions s WHERE s.id=tasks.session_id AND s.day_index>=?)) AND (? IS NULL OR EXISTS(SELECT 1 FROM sessions s WHERE s.id=tasks.session_id AND s.day_index<=?)) ORDER BY created_at").all(courseId,startDay,startDay,endDay,endDay)as any[];return{course,sessions,tasks};}
complete(reportId:string,contentMd:string,docxPath:string,pdfPath:string):void{db.prepare("UPDATE reports SET content_md=?,docx_path=?,pdf_path=?,status='completed',updated_at=? WHERE id=?").run(contentMd,docxPath,pdfPath,new Date().toISOString(),reportId)}
fail(reportId:string):void{db.prepare("UPDATE reports SET status='failed',updated_at=? WHERE id=?").run(new Date().toISOString(),reportId)} }
