import { createHash } from "node:crypto";
import { config } from "../shared/config.js";
import { getAiProvider } from "../ai/provider.js";
import { RetrievalRepository,type SearchHit } from "./retrieval.repository.js";
export class RetrievalService{
  constructor(private readonly repository:RetrievalRepository){}
  async embedSegment(segmentId:string):Promise<void>{const row=this.repository.segmentForEmbedding(segmentId);if(!row)return;const ai=getAiProvider();const [vector]=await ai.embed([row.text]);if(!vector)return;this.repository.saveEmbedding(row.courseId,"transcript",segmentId,ai.embeddingName,vector,createHash("sha256").update(row.text).digest("hex"));}
  async reindexAll():Promise<void>{const rows=this.repository.allSegmentsForEmbedding(),ai=getAiProvider();for(let offset=0;offset<rows.length;offset+=32){const batch=rows.slice(offset,offset+32),vectors=await ai.embed(batch.map(row=>row.text));batch.forEach((row,index)=>{const vector=vectors[index];if(vector)this.repository.saveEmbedding(row.courseId,"transcript",row.id,ai.embeddingName,vector,createHash("sha256").update(row.text).digest("hex"));});}}
  async search(courseId:string,question:string,limit=8):Promise<SearchHit[]>{const ai=getAiProvider();const keyword=this.repository.fts(courseId,question,limit*2);let vectorHits:SearchHit[]=[];try{const [queryVector]=await ai.embed([question]);if(queryVector){vectorHits=this.repository.vectors(courseId,ai.embeddingName).map(item=>{const hit=this.repository.hydrate(item.entityType,item.entityId);return hit?{...hit,score:cosine(queryVector,item.vector)}:null;}).filter((x):x is SearchHit=>Boolean(x)).sort((a,b)=>b.score-a.score).slice(0,limit*2);}}catch{vectorHits=[];}
    const merged=new Map<string,SearchHit>();keyword.forEach((hit,index)=>merged.set(`${hit.entityType}:${hit.entityId}`,{...hit,score:0.55*(1-index/Math.max(keyword.length,1))+0.45*hit.score}));vectorHits.forEach((hit,index)=>{const key=`${hit.entityType}:${hit.entityId}`,old=merged.get(key);merged.set(key,{...hit,score:(old?.score??0)+0.45*(1-index/Math.max(vectorHits.length,1))+0.35*hit.score});});return[...merged.values()].sort((a,b)=>b.score-a.score).slice(0,limit);}
  async answer(courseId:string,question:string):Promise<{answer:string;sources:SearchHit[]}>{const sources=await this.search(courseId,question);if(!sources.length)return{answer:"当前课堂记录中没有找到足够证据。",sources:[]};const context=sources.map((s,i)=>`[证据${i+1}] ${s.startMs===null?"知识点":formatMs(s.startMs)} ${s.content}`).join("\n");const answer=await getAiProvider().answer("你是课堂问答助手。只能根据证据回答；证据不足时明确说明。引用格式必须使用[证据N]。不要将推断写成老师原话。",`问题：${question}\n\n${context}`);return{answer,sources};}
}
function cosine(a:number[],b:number[]):number{const n=Math.min(a.length,b.length);let dot=0,aa=0,bb=0;for(let i=0;i<n;i++){dot+=a[i]!*b[i]!;aa+=a[i]!*a[i]!;bb+=b[i]!*b[i]!;}return aa&&bb?dot/Math.sqrt(aa*bb):0;}
function formatMs(ms:number):string{const t=Math.floor(ms/1000);return `${String(Math.floor(t/60)).padStart(2,"0")}:${String(t%60).padStart(2,"0")}`;}
