import { db } from "../shared/database.js";
import { id } from "../shared/ids.js";
export type SearchHit={entityType:"transcript"|"knowledge";entityId:string;content:string;score:number;startMs:number|null;sessionId:string|null};
export class RetrievalRepository{
  saveEmbedding(courseId:string,entityType:string,entityId:string,model:string,vector:number[],contentHash:string):void{const now=new Date().toISOString();db.prepare(`INSERT INTO embeddings(id,course_id,entity_type,entity_id,model,dimensions,vector_json,content_hash,created_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(entity_type,entity_id,model) DO UPDATE SET vector_json=excluded.vector_json,dimensions=excluded.dimensions,content_hash=excluded.content_hash,created_at=excluded.created_at`).run(id("emb"),courseId,entityType,entityId,model,vector.length,JSON.stringify(vector),contentHash,now);}
  segmentForEmbedding(segmentId:string):{courseId:string;text:string}|null{const r=db.prepare(`SELECT s.course_id course_id,t.text FROM transcript_segments t JOIN sessions s ON s.id=t.session_id WHERE t.id=?`).get(segmentId) as any;return r?{courseId:r.course_id,text:r.text}:null;}
  allSegmentsForEmbedding():Array<{id:string;courseId:string;text:string}>{return(db.prepare(`SELECT t.id,s.course_id,t.text FROM transcript_segments t JOIN sessions s ON s.id=t.session_id ORDER BY t.created_at`).all() as any[]).map(row=>({id:row.id,courseId:row.course_id,text:row.text}));}
  fts(courseId:string,query:string,limit=20):SearchHit[]{
    const transcript=(db.prepare(`SELECT f.segment_id entity_id,t.text content,t.start_ms,t.session_id FROM transcript_fts f JOIN transcript_segments t ON t.id=f.segment_id JOIN sessions s ON s.id=t.session_id WHERE s.course_id=? ORDER BY t.created_at DESC LIMIT 500`).all(courseId) as any[]).map(r=>({entityType:"transcript" as const,entityId:r.entity_id,content:r.content,score:lexical(query,r.content),startMs:r.start_ms,sessionId:r.session_id}));
    const knowledge=(db.prepare(`SELECT f.node_id entity_id,n.canonical_name||': '||coalesce(n.definition,'') content FROM knowledge_fts f JOIN knowledge_nodes n ON n.id=f.node_id WHERE n.course_id=? LIMIT 500`).all(courseId) as any[]).map(r=>({entityType:"knowledge" as const,entityId:r.entity_id,content:r.content,score:lexical(query,r.content),startMs:null,sessionId:null}));return [...transcript,...knowledge].filter(hit=>hit.score>0).sort((a,b)=>b.score-a.score).slice(0,limit);
  }
  vectors(courseId:string,model:string):Array<{entityType:string;entityId:string;vector:number[]}>{return(db.prepare("SELECT entity_type,entity_id,vector_json FROM embeddings WHERE course_id=? AND model=?").all(courseId,model) as any[]).map(r=>({entityType:r.entity_type,entityId:r.entity_id,vector:JSON.parse(r.vector_json)}));}
  hydrate(entityType:string,entityId:string):SearchHit|null{if(entityType==="transcript"){const r=db.prepare("SELECT id,text,start_ms,session_id FROM transcript_segments WHERE id=?").get(entityId) as any;return r?{entityType:"transcript",entityId:r.id,content:r.text,score:0,startMs:r.start_ms,sessionId:r.session_id}:null;}const r=db.prepare("SELECT id,canonical_name,definition FROM knowledge_nodes WHERE id=?").get(entityId) as any;return r?{entityType:"knowledge",entityId:r.id,content:`${r.canonical_name}: ${r.definition??""}`,score:0,startMs:null,sessionId:null}:null;}
}
function lexical(query:string,text:string):number{const q=grams(query),t=grams(text);if(!q.size||!t.size)return 0;let overlap=0;for(const term of q)if(t.has(term))overlap++;return overlap/Math.sqrt(q.size*t.size);}
function grams(value:string):Set<string>{const clean=value.normalize("NFKC").toLocaleLowerCase("zh-CN").replace(/[\s，。；：、,.!?！？()（）“”'\-]/g,"");const result=new Set<string>();for(let i=0;i<clean.length-1;i++)result.add(clean.slice(i,i+2));for(const word of value.toLocaleLowerCase("zh-CN").split(/[^a-z0-9_+]+/).filter(w=>w.length>1))result.add(word);return result;}
