import type { ClassroomTask, KnowledgeEdge, KnowledgeNode, SemanticEvent, TranscriptSegment } from "@classmate/shared";import{db}from"../shared/database.js";

export class SemanticRepository {
  insertEvent(value: SemanticEvent, fp: string): boolean { return db.prepare(`INSERT OR IGNORE INTO semantic_events(id,session_id,type,title,content,importance,confidence,deadline_raw,deadline_resolved,needs_review,evidence_json,fingerprint,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(value.id,value.sessionId,value.type,value.title,value.content,value.importance,value.confidence,value.deadlineRaw,value.deadlineResolved,value.needsReview?1:0,JSON.stringify(value.evidence),fp,value.createdAt).changes>0; }
  upsertNode(value: KnowledgeNode, normalized: string): KnowledgeNode {
    const now=new Date().toISOString(); db.prepare(`INSERT INTO knowledge_nodes(id,course_id,canonical_name,normalized_name,kind,definition,importance,confidence,evidence_count,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(course_id,normalized_name) DO UPDATE SET definition=COALESCE(excluded.definition,knowledge_nodes.definition),importance=max(knowledge_nodes.importance,excluded.importance),confidence=max(knowledge_nodes.confidence,excluded.confidence),evidence_count=knowledge_nodes.evidence_count+1,updated_at=excluded.updated_at`).run(value.id,value.courseId,value.canonicalName,normalized,value.kind,value.definition,value.importance,value.confidence,value.evidenceCount,now,now);
    const row=db.prepare("SELECT * FROM knowledge_nodes WHERE course_id=? AND normalized_name=?").get(value.courseId,normalized) as any;
    db.prepare("DELETE FROM knowledge_fts WHERE node_id=?").run(row.id); db.prepare("INSERT INTO knowledge_fts(canonical_name,definition,node_id,course_id) VALUES (?,?,?,?)").run(row.canonical_name,row.definition??"",row.id,row.course_id);
    return {id:row.id,courseId:row.course_id,canonicalName:row.canonical_name,kind:row.kind,definition:row.definition,importance:row.importance,confidence:row.confidence,evidenceCount:row.evidence_count};
  }
  insertEdge(value: KnowledgeEdge): void { db.prepare(`INSERT INTO knowledge_edges(id,course_id,source_id,target_id,relation,weight,evidence_event_id,created_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(source_id,target_id,relation) DO UPDATE SET weight=max(weight,excluded.weight),evidence_event_id=COALESCE(excluded.evidence_event_id,evidence_event_id)`).run(value.id,value.courseId,value.sourceId,value.targetId,value.relation,value.weight,value.evidenceEventId,new Date().toISOString()); }
  insertTask(value: ClassroomTask): void { const now=new Date().toISOString(); db.prepare(`INSERT OR IGNORE INTO tasks(id,course_id,session_id,title,detail,deadline_raw,deadline_resolved,status,importance,confidence,needs_review,evidence_event_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(value.id,value.courseId,value.sessionId,value.title,value.detail,value.deadlineRaw,value.deadlineResolved,value.status,value.importance,value.confidence,value.needsReview?1:0,value.evidenceEventId,now,now); }
  updateTopic(sessionId:string,topic:string):void{db.prepare("UPDATE sessions SET current_topic=? WHERE id=?").run(topic,sessionId);}
  graph(courseId:string):{nodes:KnowledgeNode[];edges:KnowledgeEdge[]}{
    const nodes=(db.prepare("SELECT * FROM knowledge_nodes WHERE course_id=? ORDER BY importance DESC LIMIT 200").all(courseId) as any[]).map(r=>({id:r.id,courseId:r.course_id,canonicalName:r.canonical_name,kind:r.kind,definition:r.definition,importance:r.importance,confidence:r.confidence,evidenceCount:r.evidence_count}));
    const ids=new Set(nodes.map(n=>n.id)); const edges=(db.prepare("SELECT * FROM knowledge_edges WHERE course_id=? ORDER BY weight DESC LIMIT 400").all(courseId) as any[]).filter(r=>ids.has(r.source_id)&&ids.has(r.target_id)).map(r=>({id:r.id,courseId:r.course_id,sourceId:r.source_id,targetId:r.target_id,relation:r.relation,weight:r.weight,evidenceEventId:r.evidence_event_id})); return {nodes,edges};
  }
  recentEvents(sessionId:string,limit=50):SemanticEvent[]{return (db.prepare("SELECT * FROM semantic_events WHERE session_id=? ORDER BY created_at DESC LIMIT ?").all(sessionId,limit) as any[]).map(r=>({id:r.id,sessionId:r.session_id,type:r.type,title:r.title,content:r.content,importance:r.importance,confidence:r.confidence,deadlineRaw:r.deadline_raw,deadlineResolved:r.deadline_resolved,needsReview:Boolean(r.needs_review),evidence:JSON.parse(r.evidence_json),createdAt:r.created_at}));}
  tasks(courseId:string):ClassroomTask[]{return (db.prepare("SELECT * FROM tasks WHERE course_id=? ORDER BY status='open' DESC, coalesce(deadline_resolved,'9999') ASC, importance DESC").all(courseId) as any[]).map(r=>({id:r.id,courseId:r.course_id,sessionId:r.session_id,title:r.title,detail:r.detail,deadlineRaw:r.deadline_raw,deadlineResolved:r.deadline_resolved,status:r.status,importance:r.importance,confidence:r.confidence,needsReview:Boolean(r.needs_review),evidenceEventId:r.evidence_event_id}));}
  updateTask(taskId:string,status:"open"|"done"|"dismissed"):ClassroomTask|null{db.prepare("UPDATE tasks SET status=?,updated_at=? WHERE id=?").run(status,new Date().toISOString(),taskId);const r=db.prepare("SELECT * FROM tasks WHERE id=?").get(taskId)as any;return r?{id:r.id,courseId:r.course_id,sessionId:r.session_id,title:r.title,detail:r.detail,deadlineRaw:r.deadline_raw,deadlineResolved:r.deadline_resolved,status:r.status,importance:r.importance,confidence:r.confidence,needsReview:Boolean(r.needs_review),evidenceEventId:r.evidence_event_id}:null;}
  sessionTasks(sessionId:string):ClassroomTask[]{return(db.prepare("SELECT * FROM tasks WHERE session_id=? ORDER BY status='open' DESC, coalesce(deadline_resolved,'9999') ASC, importance DESC").all(sessionId)as any[]).map(r=>({id:r.id,courseId:r.course_id,sessionId:r.session_id,title:r.title,detail:r.detail,deadlineRaw:r.deadline_raw,deadlineResolved:r.deadline_resolved,status:r.status,importance:r.importance,confidence:r.confidence,needsReview:Boolean(r.needs_review),evidenceEventId:r.evidence_event_id}));}
  findNode(nodeId:string):KnowledgeNode|null{const r=db.prepare("SELECT * FROM knowledge_nodes WHERE id=?").get(nodeId)as any;return r?{id:r.id,courseId:r.course_id,canonicalName:r.canonical_name,kind:r.kind,definition:r.definition,importance:r.importance,confidence:r.confidence,evidenceCount:r.evidence_count}:null;}
  updateNode(nodeId:string,patch:{definition?:string;importance?:number}):KnowledgeNode|null{const sets:string[]=[],values:any[]=[];if(patch.definition!==undefined){sets.push("definition=?");values.push(patch.definition);}if(patch.importance!==undefined){sets.push("importance=?");values.push(patch.importance);}if(!sets.length)return this.findNode(nodeId);values.push(new Date().toISOString(),nodeId);db.prepare(`UPDATE knowledge_nodes SET ${sets.join(",")},updated_at=? WHERE id=?`).run(...values);const node=this.findNode(nodeId);if(node&&patch.definition!==undefined){db.prepare("DELETE FROM knowledge_fts WHERE node_id=?").run(nodeId);db.prepare("INSERT INTO knowledge_fts(canonical_name,definition,node_id,course_id) VALUES (?,?,?,?)").run(node.canonicalName,patch.definition,nodeId,node.courseId);}return node;}
  deleteNode(nodeId:string):boolean{db.prepare("DELETE FROM knowledge_fts WHERE node_id=?").run(nodeId);db.prepare("DELETE FROM knowledge_edges WHERE source_id=? OR target_id=?").run(nodeId,nodeId);const result=db.prepare("DELETE FROM knowledge_nodes WHERE id=?").run(nodeId);return result.changes>0;}
  nodeEvidence(nodeId:string):Array<{event:SemanticEvent;segments:TranscriptSegment[]}>{const edges=db.prepare("SELECT evidence_event_id FROM knowledge_edges WHERE source_id=? OR target_id=?").all(nodeId,nodeId)as any[];const eventIds=[...new Set(edges.map(e=>e.evidence_event_id).filter(Boolean))]as string[];if(!eventIds.length)return[];const marks=eventIds.map(()=>"?").join(",");const events=(db.prepare(`SELECT * FROM semantic_events WHERE id IN (${marks})`).all(...eventIds)as any[]).map(r=>({id:r.id,sessionId:r.session_id,type:r.type,title:r.title,content:r.content,importance:r.importance,confidence:r.confidence,deadlineRaw:r.deadline_raw,deadlineResolved:r.deadline_resolved,needsReview:Boolean(r.needs_review),evidence:JSON.parse(r.evidence_json),createdAt:r.created_at}));return events.map(event=>{const segmentIds=(Array.isArray(event.evidence)?event.evidence:[]).map((e:any)=>e.transcriptId).filter(Boolean);const segments=segmentIds.length?(db.prepare(`SELECT * FROM transcript_segments WHERE id IN (${segmentIds.map(()=>"?").join(",")})`).all(...segmentIds)as any[]).map(r=>({id:r.id,sessionId:r.session_id,sequence:r.sequence,startMs:r.start_ms,endMs:r.end_ms,text:r.text,confidence:r.confidence,language:r.language,audioPath:r.audio_path,latencyMs:r.latency_ms,isFinal:Boolean(r.is_final),createdAt:r.created_at})):[];return{event,segments};});}
  nodeTasks(nodeId:string):ClassroomTask[]{const node=this.findNode(nodeId);if(!node)return[];return(db.prepare("SELECT * FROM tasks WHERE title LIKE ? OR detail LIKE ? ORDER BY status='open' DESC, importance DESC").all(`%${node.canonicalName}%`,`%${node.canonicalName}%`)as any[]).map(r=>({id:r.id,courseId:r.course_id,sessionId:r.session_id,title:r.title,detail:r.detail,deadlineRaw:r.deadline_raw,deadlineResolved:r.deadline_resolved,status:r.status,importance:r.importance,confidence:r.confidence,needsReview:Boolean(r.needs_review),evidenceEventId:r.evidence_event_id}));}
  updateTaskFull(taskId:string,patch:{title?:string;detail?:string;deadlineRaw?:string|null;deadlineResolved?:string|null;status?:"open"|"done"|"dismissed";importance?:number}):ClassroomTask|null{const sets:string[]=[],values:any[]=[];if(patch.title!==undefined){sets.push("title=?");values.push(patch.title);}if(patch.detail!==undefined){sets.push("detail=?");values.push(patch.detail);}if(patch.deadlineRaw!==undefined){sets.push("deadline_raw=?");values.push(patch.deadlineRaw);}if(patch.deadlineResolved!==undefined){sets.push("deadline_resolved=?");values.push(patch.deadlineResolved);}if(patch.status!==undefined){sets.push("status=?");values.push(patch.status);}if(patch.importance!==undefined){sets.push("importance=?");values.push(patch.importance);}if(!sets.length)return null;values.push(new Date().toISOString(),taskId);db.prepare(`UPDATE tasks SET ${sets.join(",")},updated_at=? WHERE id=?`).run(...values);const r=db.prepare("SELECT * FROM tasks WHERE id=?").get(taskId)as any;return r?{id:r.id,courseId:r.course_id,sessionId:r.session_id,title:r.title,detail:r.detail,deadlineRaw:r.deadline_raw,deadlineResolved:r.deadline_resolved,status:r.status,importance:r.importance,confidence:r.confidence,needsReview:Boolean(r.needs_review),evidenceEventId:r.evidence_event_id}:null;}
  deleteTask(taskId:string):boolean{return db.prepare("DELETE FROM tasks WHERE id=?").run(taskId).changes>0;}
  taskEvidence(taskId:string):{event:SemanticEvent;segments:TranscriptSegment[]}|null{const task=db.prepare("SELECT evidence_event_id FROM tasks WHERE id=?").get(taskId)as any;if(!task||!task.evidence_event_id)return null;const r=db.prepare("SELECT * FROM semantic_events WHERE id=?").get(task.evidence_event_id)as any;if(!r)return null;const event:SemanticEvent={id:r.id,sessionId:r.session_id,type:r.type,title:r.title,content:r.content,importance:r.importance,confidence:r.confidence,deadlineRaw:r.deadline_raw,deadlineResolved:r.deadline_resolved,needsReview:Boolean(r.needs_review),evidence:JSON.parse(r.evidence_json),createdAt:r.created_at};const segmentIds=(Array.isArray(event.evidence)?event.evidence:[]).map((e:any)=>e.transcriptId).filter(Boolean);const segments=segmentIds.length?(db.prepare(`SELECT * FROM transcript_segments WHERE id IN (${segmentIds.map(()=>"?").join(",")})`).all(...segmentIds)as any[]).map(r=>({id:r.id,sessionId:r.session_id,sequence:r.sequence,startMs:r.start_ms,endMs:r.end_ms,text:r.text,confidence:r.confidence,language:r.language,audioPath:r.audio_path,latencyMs:r.latency_ms,isFinal:Boolean(r.is_final),createdAt:r.created_at})):[];return{event,segments};}
}
