import*as SecureStore from"expo-secure-store";import{z}from"zod";import{getSettings,hashVector,saveSettings}from"@/services/database";import type{AiProvider,Analysis,MobileSettings,ReportScope}from"@/types/domain";
const KEY="classmate.openai_api_key",numField=(min:number,max:number,def:number)=>z.preprocess(v=>{if(v===null||v===undefined||v==="")return def;const n=Number(v);return Number.isNaN(n)?def:n;},z.number().min(min).max(max)),AnalysisSchema=z.object({topic:z.string().nullable().default(null),events:z.array(z.object({type:z.string(),title:z.string(),content:z.string(),importance:numField(1,10,5)})).default([]),concepts:z.array(z.object({name:z.string(),definition:z.string(),importance:numField(1,10,5)})).default([]),tasks:z.array(z.object({title:z.string(),detail:z.string(),deadlineRaw:z.string().nullable().default(null),deadlineResolved:z.string().nullable().default(null),importance:numField(1,10,5),confidence:numField(0,1,0.7),needsReview:z.boolean().default(false)})).default([])});
const normalize=(value:string)=>{const base=value.trim().replace(/\/+$/,"");return /\/v\d+$/i.test(base)?base:`${base}/v1`;};
export async function loadAiSettings():Promise<MobileSettings>{const settings=await getSettings();return{...settings,hasKey:Boolean(await SecureStore.getItemAsync(KEY))};}
export async function storeAiSettings(input:{baseUrl:string;chatModel:string;embeddingModel?:string;provider?:AiProvider;apiKey?:string}){const current=await getSettings();const settings={baseUrl:normalize(input.baseUrl),chatModel:input.chatModel.trim(),embeddingModel:input.embeddingModel?.trim()||current.embeddingModel,provider:input.provider??current.provider,apiFormat:current.apiFormat};await saveSettings(settings);if(input.apiKey?.trim())await SecureStore.setItemAsync(KEY,input.apiKey.trim(),{keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY});return{...settings,hasKey:Boolean(await SecureStore.getItemAsync(KEY))};}
async function request(path:string,init?:RequestInit){const settings=await getSettings(),key=await SecureStore.getItemAsync(KEY);if(!key)throw new Error("请先在设置中保存 API Key");const response=await fetch(`${normalize(settings.baseUrl)}${path}`,{...init,headers:{authorization:`Bearer ${key}`,...init?.headers}});if(!response.ok)throw new Error(`API 请求失败 (${response.status}): ${(await response.text()).slice(0,180)}`);return response;}
const isChatModel=(id:string)=>{const value=id.toLowerCase();if(/embed|embedding|bge|e5-|gte-|nomic|image|dall-e|whisper|transcri|audio|speech|tts/.test(value))return false;return/gpt|claude|gemini|qwen|deepseek|llama|mistral|glm|kimi|chat|o\d/.test(value);};
export async function listModels(){const settings=await getSettings();if(settings.provider==="mock")return["gpt-4o-mini","gpt-4o","deepseek-chat","qwen-plus"];const body=await(await request("/models")).json()as{data?:Array<{id?:string}>};return(body.data??[]).flatMap(item=>item.id?[item.id]:[]).filter(isChatModel).sort();}
const isEmbeddingModel=(id:string)=>{const value=id.toLowerCase();return/embed|embedding|bge|e5-|gte-|nomic/.test(value)&&!/image|dall-e|whisper|transcri|audio|speech|tts/.test(value);};
export async function listEmbeddingModels(){try{const body=await(await request("/models")).json()as{data?:Array<{id?:string}>};const filtered=(body.data??[]).flatMap(item=>item.id?[item.id]:[]).filter(isEmbeddingModel).sort();return filtered.length?filtered:["local:BAAI/bge-small-zh-v1.5","mock:hash-64"];}catch{return["local:BAAI/bge-small-zh-v1.5","mock:hash-64"];}}
export async function embed(texts:string[]):Promise<number[][]>{const settings=await getSettings();if(settings.embeddingModel.startsWith("local:")||settings.embeddingModel.startsWith("mock:"))return texts.map(hashVector);try{const response=await request("/embeddings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:settings.embeddingModel,input:texts})}),body=await response.json()as any,vectors=(body.data??[]).map((item:any)=>item.embedding).filter((v:any)=>Array.isArray(v)&&v.length>0);if(vectors.length&&vectors[0]!.length)return vectors;return texts.map(hashVector);}catch{return texts.map(hashVector);}}
export async function testEmbeddingModel(){const settings=await getSettings();if(settings.embeddingModel.startsWith("local:")||settings.embeddingModel.startsWith("mock:")){const vectors=await embed(["测试连接"]);return`向量维度 ${vectors[0]!.length}（本地哈希）`;}try{const response=await request("/embeddings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:settings.embeddingModel,input:["测试连接"]})}),body=await response.json()as any,vectors=(body.data??[]).map((item:any)=>item.embedding).filter((v:any)=>Array.isArray(v)&&v.length>0);if(!vectors.length||!vectors[0]!.length){const fallback=hashVector("测试连接");return`API 返回空，已回退本地哈希（维度 ${fallback.length}）`;}return`向量维度 ${vectors[0]!.length}`;}catch(error){const fallback=hashVector("测试连接");return`API 不可用，已回退本地哈希（维度 ${fallback.length}）`;}}
function mockChat(system:string):string{if(system.includes("连接测试"))return"OK";if(system.includes("课堂事实抽取器"))return JSON.stringify({topic:"模拟课堂主题",events:[{type:"KEYPOINT",title:"模拟重点",content:"这是模拟的重点内容",importance:7}],concepts:[{name:"模拟概念",definition:"这是模拟概念定义",importance:6}],tasks:[{title:"模拟任务",detail:"完成模拟实验报告",deadlineRaw:"下周五",deadlineResolved:new Date(Date.now()+5*86400000).toISOString().slice(0,10),importance:8,confidence:.6,needsReview:true}]});if(system.includes("课堂问答助手"))return"根据[证据1]，模拟回答：这是一个测试回复。";if(system.includes("学习报告编辑"))return"# 模拟学习报告\n\n## 学习目的\n这是 mock 模式生成的模拟报告，用于离线验证完整流程。\n\n## 核心知识\n- 模拟知识点一\n- 模拟知识点二\n\n## 任务与实践\n- 完成模拟实验\n\n## 反思\nmock 模式下无需真实 API 即可验证界面与数据流。\n\n## 总结\nmock 模式测试完成。";return"这是模拟回复（mock 模式）。";}
export async function chat(system:string,prompt:string){const settings=await getSettings();if(settings.provider==="mock")return mockChat(system);const response=await request("/chat/completions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:settings.chatModel,messages:[{role:"system",content:system},{role:"user",content:prompt}],temperature:.2})}),body=await response.json()as any,content=body.choices?.[0]?.message?.content;if(typeof content!=="string"||!content.trim())throw new Error("模型返回空内容");return content.trim();}
export async function testSelectedModel(){return chat("你是连接测试助手。","只回复 OK");}
export async function analyzeTranscript(text:string):Promise<Analysis>{const raw=await chat("你是课堂事实抽取器。只依据字幕输出JSON，不添加外部知识。字段为topic、events、concepts、tasks。事件含type,title,content,importance；概念含name,definition,importance；任务含title,detail,deadlineRaw(老师原话),deadlineResolved(ISO日期或null),importance,confidence(0-1),needsReview(无法精确解析日期时为true)。解析相对日期如'下周五'时基于当前日期推算。","字幕：\n"+text),clean=raw.replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"");return AnalysisSchema.parse(JSON.parse(clean));}
export async function answerFromEvidence(question:string,evidence:Array<{text:string;startMs:number}>){if(!evidence.length)return"当前课堂记录中没有找到足够证据。";return chat("你是课堂问答助手。只能依据证据回答，必须使用[证据N]引用；证据不足时明确说明。",`问题：${question}\n\n${evidence.map((item,index)=>`[证据${index+1}] ${Math.floor(item.startMs/60000)}:${String(Math.floor(item.startMs/1000)%60).padStart(2,"0")} ${item.text}`).join("\n")}`);}
export async function generateSessionSummary(transcripts:Array<{text:string;startMs:number}>):Promise<string>{if(!transcripts.length)return"当前课堂暂无字幕记录。";const context=transcripts.map((item,index)=>`[${index+1}] ${Math.floor(item.startMs/60000)}:${String(Math.floor(item.startMs/1000)%60).padStart(2,"0")} ${item.text}`).join("\n");return chat("你是课堂摘要助手。依据字幕生成结构化摘要：当日主题、核心知识、老师强调、任务与待确认事项、当日反思。不添加外部知识，不把老师布置的任务写成学生已完成。输出 Markdown。",`请为以下课堂字幕生成分层增量摘要：\n\n${context}`);}
export async function generateLearningReport(scope:ReportScope,context:string,evidenceCount:number){const days=Math.max(1,Math.floor((Date.parse(scope.endDate)-Date.parse(scope.startDate))/86400000)+1),long=scope.template==="course"||scope.template==="practicum"||scope.template==="custom"||days>=7,structure={daily:"当日主题、核心知识、老师强调、任务与待确认事项、当日反思",weekly:"本周概览、按日进展、核心知识、任务与截止时间、问题与反思、下周关注",course:"学习目标、课程范围与方法、阶段进展、核心知识体系、任务与实践、学习反思、总结",practicum:"实训目的、环境与方法、范围内每日内容、核心知识、任务与实践、学习反思、总结",custom:"范围概览、内容进展、核心知识、任务与实践、反思、总结"}[scope.template],target=long?"约 2600 至 3400 个中文字符，正文至少 2000 个非空白字符":"根据证据量写成紧凑完整的报告，不重复凑字数",system="你是学习报告编辑。只能依据给定课堂证据撰写，不补充未出现的课程事实，不把老师布置的任务写成学生已完成。每个事实段落使用[证据N]引用；证据不足时写明待确认。输出 Markdown。",prompt=`报告标题：${scope.title}\n模板：${scope.template}\n日期范围：${scope.startDate} 至 ${scope.endDate}\n证据数：${evidenceCount}\n结构：${structure}\n长度：${target}\n\n课堂证据：\n${context}`;let content=await chat(system,prompt);if(long&&content.replace(/\s/g,"").length<2000)content=await chat(system,`请在不增加新事实的前提下重写并充实以下报告，使结构完整且正文达到至少2000个非空白字符。保留并核对[证据N]引用，不得用重复句凑字数。\n\n${prompt}\n\n已有草稿：\n${content}`);return content;}
